<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-EJE643E" failures="1" tests="3" name="Login Tests1" time="5.374" errors="0" timestamp="2024-04-28T12:33:04 CDT">
  <testcase classname="Tests1" name="doLogin3" time="1.109"/>
  <testcase classname="Tests1" name="doLogin2" time="0.852"/>
  <testcase classname="Tests1" name="doLogin1" time="0.808">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [16] but found [15]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [16] but found [15]
at Tests1.doLogin1(Tests1.java:48)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- doLogin1 -->
</testsuite> <!-- Login Tests1 -->
